### ISSUE TITLE
Does not work with nodejs 0.10.14

### ISSUE THREAD

**Issue by clercm** [ramr/nodejs-custom-version-openshift#6]
Nodejs 0.10.13 compiles and run fine, but .14 fails with this compilation error:
`remote: /var/lib/openshift/51edf9e0e0b8cd9b2c0000d4/app-root/data//node-v0.10.14-linux-x64/bin/node: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /var/lib/openshift/51edf9e0e0b8cd9b2c0000d4/app-root/data//node-v0.10.14-linux-x64/bin/node)
remote: /var/lib/openshift/51edf9e0e0b8cd9b2c0000d4/app-root/data//node-v0.10.14-linux-x64/bin/node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/openshift/51edf9e0e0b8cd9b2c0000d4/app-root/data//node-v0.10.14-linux-x64/bin/node)
remote: An error occurred executing 'gear postreceive' (exit code: 1)`
